answered question 2
billythakidd04/ecc-wtf-web-dev pull request #10
Opened 2021-02-18 23:54 UTC by eiman-kased

answered question 2.

2021-02-18 23:58 UTC, cwlainson approved these changes

2021-02-19 00:01 UTC, billythakidd04 requested changes

2021-02-19 00:01 UTC, billythakidd04 commented on Pop_Quiz.txt
> +git add .
@eiman-kased what is the other option. add both please.

2021-02-19 00:22 UTC, billythakidd04 approved these changes

2021-02-19 00:22 UTC, merged