added week 6 js start, will update as week continues
billythakidd04/ecc-wtf-web-dev pull request #35
Opened 2021-03-10 17:06 UTC by billythakidd04

Added a markdown page with the link to the slides, also added some very basic js to my page
Please note the js/ directory as that is where your scripts should live.

2021-03-10 17:21 UTC, eiman-kased requested changes
Line 16 in Week_6_JS/css/nav.css has an extra semi-colon

2021-03-10 19:58 UTC, vricci518 submitted a review, later dismissed

2021-03-10 20:28 UTC, billythakidd04 commented
> Line 16 in Week_6_JS/css/nav.css has an extra semi-colon

nice catch @eiman-kased, fixed

2021-03-10 20:39 UTC, nburd90 approved these changes

2021-03-10 20:47 UTC, rbaia28 approved these changes

2021-03-10 20:48 UTC, gc824 approved these changes

2021-03-10 20:57 UTC, margeschrec approved these changes

2021-03-10 22:10 UTC, eiman-kased approved these changes

2021-03-11 01:31 UTC, vricci518 approved these changes

2021-03-12 01:55 UTC, merged